### ISSUE TITLE
Specific list outputs almost empty .csv

### ISSUE THREAD

**Issue by 2V3EvG4LMJFdRe** [L-Dot/Letterboxd-list-scraper#8]
[This list](https://letterboxd.com/acervofilmico/list/chile-feature-films-largometraje-chileno/) outputs a .csv with only one entry. I've attempted it twice. All the other lists I've tried seem to have outputted everything right.

**Comment by L-Dot** [comment]
It seems this bug was fixed in [v2.1.0](https://github.com/L-Dot/Letterboxd-list-scraper/releases/tag/v2.1.0) while I was working on fixing issue #12. Please see my comment there for an explanation.

Your list was tested and gave good output, so I'll close this issue for now.
