### ISSUE TITLE
help me...

### ISSUE THREAD

**Issue by lhsb232** [L-Dot/Letterboxd-list-scraper#9]
hi guys, i dont know anything about python or codes, but this is incredible. I really wanna figure out how i can make this work, but i'am so dumb. Someone could explaine better or give me another way. Just for the record this is incredible e i'trying alot but i "old guy" not tecnology guy. However study cinema is basicaly organization and this program help me alot! Thanks and any help is welcome.

**Comment by L-Dot** [comment]
Hi! Thank you for liking the project. Unfortunately at the moment there is not really an easier way to use the program. If you want to try and use it yourself you can find a lot of helpful documentation and videos online about how to install Python and how to download and run Python scripts from GitHub. Maybe start there. Example: https://www.quora.com/How-do-I-run-a-Python-script-that-I-downloaded-from-GitHub.

I'd love to help more but it's a lot to explain in one comment. Do let me know if you get stuck.
